//! 数据包代码生成。
//!
//! 入口是 [`Compiler`]：先为每个用户函数调用一次 [`Compiler::compile_block`]，
//! 再合成 load 函数，最后由 [`Compiler::finish`] 落盘为 [`CompiledPack`]。
//! 具体下降逻辑按职责拆分成子模块：
//!
//! - [`statements`]：控制流（each/if/while/call 等）与辅助函数分配；
//! - [`actions`]：`give` 与 `self` 实体操作；
//! - [`expressions`]：表达式与条件求值，以及临时计分项；
//! - [`names`]：假玩家、objective 和稳定哈希命名；
//! - [`emit`]：Minecraft 命令片段与 JSON 文本的格式化。

mod actions;
mod emit;
mod expressions;
mod names;
mod statements;

use std::collections::{BTreeMap, HashMap};
use std::path::PathBuf;

use crate::ast::*;

use super::CompiledPack;
use emit::{empty_slot_source, pack_metadata, tag_json};
use names::{build_holders, objective_name};

/// 表达式求值结果：编译期整数或运行时计分项。
#[derive(Clone)]
enum Value {
    Integer(i32),
    Score(String),
}

/// 单次代码生成的完整状态。
pub(super) struct Compiler<'a> {
    program: &'a Program,
    objective: String,
    /// `<函数名, 变量名> -> 假玩家`，构造时一次算好。
    holders: HashMap<(&'a str, &'a str), String>,
    functions: BTreeMap<String, Vec<String>>,
    helper_counters: HashMap<String, usize>,
    temporary_counter: usize,
    /// 是否使用了 `give(..., self.item)` 需要的空槽来源资源。
    uses_empty_slot: bool,
}

impl<'a> Compiler<'a> {
    pub(super) fn new(program: &'a Program) -> Self {
        Self {
            program,
            objective: objective_name(&program.namespace),
            holders: build_holders(program),
            functions: BTreeMap::new(),
            helper_counters: HashMap::new(),
            temporary_counter: 0,
            uses_empty_slot: false,
        }
    }

    /// 下降全部用户函数，并合成负责初始化的 `__mcl/load` 函数。
    pub(super) fn compile_functions(&mut self) {
        for function in &self.program.functions {
            let commands = self.compile_block(&function.body, &function.name);
            self.functions.insert(function.name.clone(), commands);
        }

        let load_functions = self
            .program
            .functions
            .iter()
            .filter(|function| function.attributes.contains(&Attribute::Load))
            .collect::<Vec<_>>();
        let mut commands = vec![format!(
            "scoreboard objectives add {} dummy",
            self.objective
        )];
        for score in &self.program.scores {
            commands.push(format!(
                "execute unless score {} {} = {} {} run scoreboard players set {} {} {}",
                names::score_holder(&score.name),
                self.objective,
                names::score_holder(&score.name),
                self.objective,
                names::score_holder(&score.name),
                self.objective,
                score.initial
            ));
        }
        for storage in &self.program.storages {
            commands.push(format!(
                "execute unless data storage {} {} run data modify storage {} {} set value []",
                storage.storage_id, storage.path, storage.storage_id, storage.path
            ));
        }
        for function in load_functions {
            commands.push(format!(
                "function {}:{}",
                self.program.namespace, function.name
            ));
        }
        self.functions.insert("__mcl/load".to_owned(), commands);
    }

    /// 生成 `pack.mcmeta`、函数文件、资源文件和 load/tick 标签。
    pub(super) fn finish(self, description: &str) -> CompiledPack {
        let mut files = BTreeMap::new();
        files.insert(PathBuf::from("pack.mcmeta"), pack_metadata(description));
        if self.uses_empty_slot {
            files.insert(
                PathBuf::from("data")
                    .join(&self.program.namespace)
                    .join("slot_source")
                    .join("__mcl/empty_slot.json"),
                empty_slot_source().to_owned(),
            );
        }
        for (name, commands) in self.functions {
            let path = PathBuf::from("data")
                .join(&self.program.namespace)
                .join("function")
                .join(format!("{name}.mcfunction"));
            let mut contents = "# Generated by mclang.\n".to_owned();
            if !commands.is_empty() {
                contents.push_str(&commands.join("\n"));
                contents.push('\n');
            }
            files.insert(path, contents);
        }
        for resource in &self.program.resources {
            let value = serde_json::from_str::<serde_json::Value>(&resource.json)
                .expect("semantic validation guarantees valid JSON");
            let contents = serde_json::to_string_pretty(&value)
                .expect("a parsed JSON value can always be serialized")
                + "\n";
            files.insert(
                PathBuf::from("data")
                    .join(&self.program.namespace)
                    .join(&resource.kind)
                    .join(format!("{}.json", resource.name)),
                contents,
            );
        }

        files.insert(
            PathBuf::from("data/minecraft/tags/function/load.json"),
            tag_json(&[format!("{}:__mcl/load", self.program.namespace)]),
        );
        let ticks = self
            .program
            .functions
            .iter()
            .filter(|function| function.attributes.contains(&Attribute::Tick))
            .map(|function| format!("{}:{}", self.program.namespace, function.name))
            .collect::<Vec<_>>();
        if !ticks.is_empty() {
            files.insert(
                PathBuf::from("data/minecraft/tags/function/tick.json"),
                tag_json(&ticks),
            );
        }
        CompiledPack { files }
    }
}
