/// Shared command methods and finite options; kept out of the reserved-word set.
pub(crate) fn command_value(value: &str) -> Option<&'static str> {
    match value {
        "integer" | "整数" => Some("integer"),
        "decimal" | "小数" => Some("decimal"),
        "has" | "存在" => Some("has"),
        "equals" | "等于" => Some("equals"),
        "matches" | "匹配" => Some("matches"),
        "give" | "给予" => Some("give"),
        "take" | "收回" => Some("take"),
        "enable" | "启用" => Some("enable"),
        "disable" | "停用" => Some("disable"),
        "first" | "最前" => Some("first"),
        "last" | "最后" => Some("last"),
        "before" | "之前" => Some("before"),
        "after" | "之后" => Some("after"),
        "available" | "可用" => Some("available"),
        "enabled" | "已启用" => Some("enabled"),
        "roll" | "掷出" => Some("roll"),
        "table" | "表" => Some("table"),
        "fish" | "钓鱼" => Some("fish"),
        "mine" | "挖掘" => Some("mine"),
        "insert" | "插入" => Some("insert"),
        "replace" | "替换" => Some("replace"),
        "add" | "添加" => Some("add"),
        "remove" | "移除" => Some("remove"),
        "list" | "列出" => Some("list"),
        "get" | "取" => Some("get"),
        "set" | "设置" => Some("set"),
        "reset" | "重置" => Some("reset"),
        "base" | "基值" => Some("base"),
        "modifier" | "修饰器" => Some("modifier"),
        "value" | "数值" => Some("value"),
        "mount" | "骑上" => Some("mount"),
        "dismount" | "下乘" => Some("dismount"),
        "to" | "转向" => Some("to"),
        "facing" | "面向" => Some("facing"),
        "by" | "由" => Some("by"),
        "from" | "来源" => Some("from"),
        "under" | "低于" => Some("under"),
        "feet" | "脚部" => Some("feet"),
        "eyes" | "眼部" => Some("eyes"),
        "mainhand" | "主手" => Some("mainhand"),
        "offhand" | "副手" => Some("offhand"),
        "none" | "无" => Some("none"),
        "whack" | "挥击" => Some("whack"),
        "stab" | "刺击" => Some("stab"),
        "survival" | "生存" => Some("survival"),
        "creative" | "创造" => Some("creative"),
        "adventure" | "冒险" => Some("adventure"),
        "spectator" | "旁观者" => Some("spectator"),
        "peaceful" | "和平" => Some("peaceful"),
        "easy" | "简单" => Some("easy"),
        "normal" | "普通" => Some("normal"),
        "hard" | "困难" => Some("hard"),
        "add_value" | "增加数值" => Some("add_value"),
        "add_multiplied_base" | "增加基值倍率" => Some("add_multiplied_base"),
        "add_multiplied_total" | "增加总值倍率" => Some("add_multiplied_total"),
        "empty" | "清空" => Some("empty"),
        "join" | "加入" => Some("join"),
        "leave" | "离开" => Some("leave"),
        "modify" | "修改" => Some("modify"),
        "display_name" | "显示名" => Some("display_name"),
        "prefix" | "前缀" => Some("prefix"),
        "suffix" | "后缀" => Some("suffix"),
        "color" | "颜色" => Some("color"),
        "hex" | "十六进制" => Some("hex"),
        "style" | "样式" => Some("style"),
        "friendly_fire" | "友军伤害" => Some("friendly_fire"),
        "see_friendly_invisibles" | "看见隐身队友" => Some("see_friendly_invisibles"),
        "nametag_visibility" | "名称可见性" => Some("nametag_visibility"),
        "death_message_visibility" | "死亡消息可见性" => Some("death_message_visibility"),
        "collision_rule" | "碰撞规则" => Some("collision_rule"),
        "always" | "总是" => Some("always"),
        "never" | "从不" => Some("never"),
        "hide_for_other_teams" | "对其他队伍隐藏" => Some("hide_for_other_teams"),
        "hide_for_own_team" | "对本队隐藏" => Some("hide_for_own_team"),
        "push_own_team" | "碰撞本队" => Some("push_own_team"),
        "push_other_teams" | "碰撞其他队伍" => Some("push_other_teams"),
        _ => super::text_color(value),
    }
}

/// 界面命令的子命令与取值；单独成表，避免文档双语翻译把 `players`
/// 这样的普通查询名当成全局命令枚举。
pub(crate) fn ui_value(value: &str) -> Option<&'static str> {
    match value {
        "subtitle" | "副标题" => Some("subtitle"),
        "name" | "名称" => Some("name"),
        "actionbar" | "动作栏" => Some("actionbar"),
        "times" | "显示时间" => Some("times"),
        "max" | "最大值" => Some("max"),
        "visible" | "可见" => Some("visible"),
        "players" | "玩家列表" => Some("players"),
        "pink" | "粉色" => Some("pink"),
        "purple" | "紫色" => Some("purple"),
        "progress" | "连续进度条" => Some("progress"),
        "notched_6" | "六格" => Some("notched_6"),
        "notched_10" | "十格" => Some("notched_10"),
        "notched_12" | "十二格" => Some("notched_12"),
        "notched_20" | "二十格" => Some("notched_20"),
        "show" | "显示对话框" => Some("show"),
        "force" | "强制" => Some("force"),
        _ => None,
    }
}
