//! 面向工具的分析入口：对一组内存源文件做完整检查，并给出结构化诊断与符号表。
//!
//! [`analyze`] 供语言服务器、编辑器插件等调用方使用：输入可以来自磁盘，也可以来自
//! 未保存的编辑器缓冲区；输出不依赖任何渲染字符串，每条诊断都带具体的文件路径和
//! 字节范围。命令行入口 [`crate::check_file`] 与 [`crate::build_file`] 复用本模块的
//! [`parse_all`] 和 [`merge_programs`]，保证两边看到完全相同的语法与语义检查结果。

use std::path::PathBuf;

use crate::ast;
use crate::compiler::compile;
use crate::diagnostic::Diagnostic;
use crate::lexer::lex;
use crate::parser::parse;

pub use crate::ast::Span;

/// 一份待分析的源文件。`path` 只用于标识来源，不要求文件真实存在。
#[derive(Debug)]
pub struct SourceFile {
    pub path: PathBuf,
    pub text: String,
}

/// 一条带有来源文件的结构化诊断。`span` 是文件内的字节范围。
#[derive(Debug)]
pub struct FileDiagnostic {
    pub path: PathBuf,
    pub message: String,
    pub span: Span,
}

/// 符号种类的显示名称，供补全与悬停文本使用。
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SymbolKind {
    Function,
    Score,
    Query,
    ItemStack,
    Storage,
    Resource,
    FunctionTag,
    Parameter,
    Local,
}

impl SymbolKind {
    pub fn label(self) -> &'static str {
        match self {
            Self::Function => "函数",
            Self::Score => "计分变量",
            Self::Query => "实体查询",
            Self::ItemStack => "物品定义",
            Self::Storage => "物品存储",
            Self::Resource => "JSON 资源",
            Self::FunctionTag => "函数标签",
            Self::Parameter => "参数",
            Self::Local => "局部变量",
        }
    }
}

/// 可补全、可悬停、可跳转的名称。
#[derive(Debug)]
pub struct Symbol {
    pub name: String,
    pub kind: SymbolKind,
    pub path: PathBuf,
    /// 名称本身的范围，跳转与悬停高亮使用它。
    pub name_span: Span,
    /// 所属函数体范围；参数与局部变量只在其中可见，顶层声明为 `None`。
    pub scope: Option<Span>,
    /// 面向人类的声明摘要，例如 `fn tick() -> score`。
    pub detail: String,
}

/// 一次完整分析的结果：诊断可以为空，符号表在语法错误时可能不完整。
#[derive(Debug, Default)]
pub struct ProjectAnalysis {
    pub diagnostics: Vec<FileDiagnostic>,
    pub symbols: Vec<Symbol>,
}

/// 对一组源文件做词法、语法、跨文件合并与语义检查，返回全部诊断与已声明的符号。
pub fn analyze(sources: &[SourceFile]) -> ProjectAnalysis {
    let (programs, mut diagnostics) = parse_all(sources);
    let symbols = collect_symbols(sources, &programs);

    if diagnostics.is_empty() {
        match merge_programs(programs) {
            Ok(program) => {
                if let Err(mut errors) = compile(&program, "Generated by mclang") {
                    diagnostics.append(&mut errors);
                }
            }
            Err(mut errors) => diagnostics.append(&mut errors),
        }
    }

    let diagnostics = diagnostics
        .into_iter()
        .filter_map(|diagnostic| {
            let source = sources.get(diagnostic.span.source)?;
            Some(FileDiagnostic {
                path: source.path.clone(),
                message: diagnostic.message,
                span: diagnostic.span,
            })
        })
        .collect();
    ProjectAnalysis {
        diagnostics,
        symbols,
    }
}

/// 按源文件顺序解析所有文件，返回解析成功的程序与全部词法/语法诊断。
pub(crate) fn parse_all(sources: &[SourceFile]) -> (Vec<(usize, ast::Program)>, Vec<Diagnostic>) {
    let mut programs = Vec::new();
    let mut diagnostics = Vec::new();
    for (source_id, source) in sources.iter().enumerate() {
        match lex(&source.text, source_id) {
            Ok(tokens) => match parse(tokens) {
                Ok(program) => programs.push((source_id, program)),
                Err(mut errors) => diagnostics.append(&mut errors),
            },
            Err(mut errors) => diagnostics.append(&mut errors),
        }
    }
    (programs, diagnostics)
}

/// 合并多文件程序并检查命名空间一致性。
pub(crate) fn merge_programs(
    programs: Vec<(usize, ast::Program)>,
) -> Result<ast::Program, Vec<Diagnostic>> {
    let mut diagnostics = Vec::new();
    let mut programs = programs.into_iter().map(|(_, program)| program);
    let Some(mut program) = programs.next() else {
        diagnostics.push(Diagnostic::new(
            "项目里没有任何 .mcl 源文件",
            Span {
                source: 0,
                start: 0,
                end: 0,
            },
        ));
        return Err(diagnostics);
    };
    for mut other in programs {
        if other.namespace != program.namespace {
            diagnostics.push(Diagnostic::new(
                format!(
                    "项目命名空间必须一致：预期 `{}`，实际为 `{}`",
                    program.namespace, other.namespace
                ),
                other.namespace_span,
            ));
        }
        program.scores.append(&mut other.scores);
        program.queries.append(&mut other.queries);
        program.item_stacks.append(&mut other.item_stacks);
        program.storages.append(&mut other.storages);
        program.resources.append(&mut other.resources);
        program.function_tags.append(&mut other.function_tags);
        program.functions.append(&mut other.functions);
    }
    if diagnostics.is_empty() {
        Ok(program)
    } else {
        Err(diagnostics)
    }
}

fn collect_symbols(sources: &[SourceFile], programs: &[(usize, ast::Program)]) -> Vec<Symbol> {
    let mut symbols = Vec::new();
    for (source_id, program) in programs {
        let Some(source) = sources.get(*source_id) else {
            continue;
        };
        let path = &source.path;
        for score in &program.scores {
            symbols.push(Symbol {
                name: score.name.clone(),
                kind: SymbolKind::Score,
                path: path.clone(),
                name_span: score.name_span,
                scope: None,
                detail: format!("score {} = {}", score.name, score.initial),
            });
        }
        for query in &program.queries {
            symbols.push(Symbol {
                name: query.name.clone(),
                kind: SymbolKind::Query,
                path: path.clone(),
                name_span: query.name_span,
                scope: None,
                detail: format!("query {} = entity({:?})", query.name, query.entity_type),
            });
        }
        for item in &program.item_stacks {
            symbols.push(Symbol {
                name: item.name.clone(),
                kind: SymbolKind::ItemStack,
                path: path.clone(),
                name_span: item.name_span,
                scope: None,
                detail: format!("item {} = item_stack({:?})", item.name, item.item_id),
            });
        }
        for storage in &program.storages {
            symbols.push(Symbol {
                name: storage.name.clone(),
                kind: SymbolKind::Storage,
                path: path.clone(),
                name_span: storage.name_span,
                scope: None,
                detail: format!(
                    "storage {} = item_list({:?}, {:?})",
                    storage.name, storage.storage_id, storage.path
                ),
            });
        }
        for resource in &program.resources {
            symbols.push(Symbol {
                name: resource.name.clone(),
                kind: SymbolKind::Resource,
                path: path.clone(),
                name_span: resource.name_span,
                scope: None,
                detail: format!("resource {} {}", resource.kind, resource.name),
            });
        }
        for tag in &program.function_tags {
            symbols.push(Symbol {
                name: tag.name.clone(),
                kind: SymbolKind::FunctionTag,
                path: path.clone(),
                name_span: tag.name_span,
                scope: None,
                detail: format!("fn_tag {}", tag.name),
            });
        }
        for function in &program.functions {
            symbols.push(Symbol {
                name: function.name.clone(),
                kind: SymbolKind::Function,
                path: path.clone(),
                name_span: function.name_span,
                scope: None,
                detail: function_detail(function),
            });
            for parameter in &function.parameters {
                symbols.push(Symbol {
                    name: parameter.name.clone(),
                    kind: SymbolKind::Parameter,
                    path: path.clone(),
                    name_span: parameter.span,
                    scope: Some(function.span),
                    detail: format!("fn {} 的参数", function.name),
                });
            }
            collect_locals(path, function, &function.body, &mut symbols);
        }
    }
    symbols
}

fn function_detail(function: &ast::Function) -> String {
    let parameters = function
        .parameters
        .iter()
        .map(|parameter| parameter.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let returns = if function.returns_score {
        " -> score"
    } else {
        ""
    };
    format!("fn {}({parameters}){returns}", function.name)
}

/// `let` 局部变量只在其所属函数体内可见，因此只登记名称与可见范围。
fn collect_locals(
    path: &PathBuf,
    function: &ast::Function,
    statements: &[ast::Statement],
    symbols: &mut Vec<Symbol>,
) {
    for statement in statements {
        match &statement.kind {
            ast::StatementKind::Let {
                name, name_span, ..
            } => symbols.push(Symbol {
                name: name.clone(),
                kind: SymbolKind::Local,
                path: path.clone(),
                name_span: *name_span,
                scope: Some(function.span),
                detail: format!("let {name}"),
            }),
            ast::StatementKind::Each { body, .. }
            | ast::StatementKind::InDimension { body, .. }
            | ast::StatementKind::Spawn { body, .. }
            | ast::StatementKind::Execute { body, .. }
            | ast::StatementKind::While { body, .. } => {
                collect_locals(path, function, body, symbols);
            }
            ast::StatementKind::If {
                then_body,
                else_body,
                ..
            } => {
                collect_locals(path, function, then_body, symbols);
                collect_locals(path, function, else_body, symbols);
            }
            _ => {}
        }
    }
}
