//! 面向工具的分析入口：对一组内存源文件做完整检查，并给出结构化诊断与符号表。
//!
//! [`analyze`] 供语言服务器、编辑器插件等调用方使用：输入可以来自磁盘，也可以来自
//! 未保存的编辑器缓冲区；输出不依赖任何渲染字符串，每条诊断都带具体的文件路径和
//! 字节范围。命令行入口 [`crate::check_file`] 与 [`crate::build_file`] 复用本模块的
//! [`parse_all`] 与 [`crate::modules::resolve`]，保证两边看到完全相同的语法与语义检查结果。
//!
//! 模块系统就位后，一组源文件会先按“最近的 main.mcl 祖先”分组，每个项目
//! 各自沿 `import` 解析；不属于任何入口的单个 `.mcl` 文件按单文件项目的入口处理。

use std::collections::{BTreeMap, HashMap, HashSet};
use std::path::PathBuf;

use crate::ast;
use crate::compiler::compile;
use crate::diagnostic::Diagnostic;
use crate::lexer::lex;
use crate::parser::parse;

pub use crate::ast::Span;

/// 一份待分析的源文件。`path` 只用于标识来源，不要求文件真实存在。
#[derive(Debug)]
pub struct SourceFile {
    pub path: PathBuf,
    pub text: String,
}

/// 一条带有来源文件的结构化诊断。`span` 是文件内的字节范围。
#[derive(Debug)]
pub struct FileDiagnostic {
    pub path: PathBuf,
    pub message: String,
    pub span: Span,
}

/// 符号种类的显示名称，供补全与悬停文本使用。
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SymbolKind {
    Function,
    Score,
    Objective,
    Query,
    ItemStack,
    Storage,
    DataSlot,
    Resource,
    Advancement,
    FunctionTag,
    Parameter,
    Local,
}

impl SymbolKind {
    pub fn label(self) -> &'static str {
        match self {
            Self::Function => "函数",
            Self::Score => "计分变量",
            Self::Objective => "计分板目标",
            Self::Query => "实体查询",
            Self::ItemStack => "物品定义",
            Self::Storage => "物品存储",
            Self::DataSlot => "数据槽",
            Self::Resource => "JSON 资源",
            Self::Advancement => "进度",
            Self::FunctionTag => "函数标签",
            Self::Parameter => "参数",
            Self::Local => "局部变量",
        }
    }
}

/// 可补全、可悬停、可跳转的名称。
#[derive(Debug)]
pub struct Symbol {
    pub name: String,
    pub kind: SymbolKind,
    pub path: PathBuf,
    /// 名称本身的范围，跳转与悬停高亮使用它。
    pub name_span: Span,
    /// 所属函数体范围；参数与局部变量只在其中可见，顶层声明为 `None`。
    pub scope: Option<Span>,
    /// 面向人类的声明摘要，例如 `fn tick() -> score`。
    pub detail: String,
}

/// 一次完整分析的结果：诊断可以为空，符号表在语法错误时可能不完整。
#[derive(Debug, Default)]
pub struct ProjectAnalysis {
    pub diagnostics: Vec<FileDiagnostic>,
    pub symbols: Vec<Symbol>,
}

/// 对一组源文件做词法、语法、模块解析与语义检查，返回全部诊断与已声明的符号。
pub fn analyze(sources: &[SourceFile]) -> ProjectAnalysis {
    let mut expanded = sources
        .iter()
        .map(|source| SourceFile {
            path: source.path.clone(),
            text: source.text.clone(),
        })
        .collect::<Vec<_>>();
    let mut groups = project_groups(sources);
    let (mut programs, mut diagnostics) = parse_all(&expanded);
    let parsed_source_count = expanded.len();
    add_standard_modules(&mut expanded, &mut groups, &programs);
    if expanded.len() > parsed_source_count {
        let (mut standard_programs, mut standard_diagnostics) =
            parse_from(&expanded, parsed_source_count);
        programs.append(&mut standard_programs);
        diagnostics.append(&mut standard_diagnostics);
    }
    let symbols = collect_symbols(&expanded, &programs);

    if diagnostics.is_empty() {
        let mut root_by_member = HashMap::new();
        for (root, members) in &groups {
            for member in members {
                root_by_member.insert(*member, *root);
            }
        }
        let mut programs_by_root: BTreeMap<usize, Vec<(usize, ast::Program)>> = BTreeMap::new();
        for (index, program) in programs {
            if let Some(root) = root_by_member.get(&index) {
                programs_by_root
                    .entry(*root)
                    .or_default()
                    .push((index, program));
            }
        }
        for (root, _) in groups {
            let group = programs_by_root.remove(&root).unwrap_or_default();
            match crate::modules::resolve(group, &expanded, root) {
                Ok(mut program) => {
                    if let Err(mut errors) = compile(
                        &mut program,
                        &crate::compiler::CompileOptions {
                            description: "Generated by mclang".into(),
                        },
                    ) {
                        diagnostics.append(&mut errors);
                    }
                }
                Err(mut errors) => diagnostics.append(&mut errors),
            }
        }
    }

    let diagnostics = diagnostics
        .into_iter()
        .filter_map(|diagnostic| {
            let source = expanded.get(diagnostic.span.source)?;
            Some(FileDiagnostic {
                path: source.path.clone(),
                message: diagnostic.message,
                span: diagnostic.span,
            })
        })
        .collect();
    ProjectAnalysis {
        diagnostics,
        symbols,
    }
}

/// Mirror the CLI's embedded-module loading for unsaved editor buffers.
fn add_standard_modules(
    sources: &mut Vec<SourceFile>,
    groups: &mut [(usize, HashSet<usize>)],
    programs: &[(usize, ast::Program)],
) {
    let programs_by_source: HashMap<usize, &ast::Program> =
        programs.iter().map(|(index, program)| (*index, program)).collect();
    for (root, members) in groups {
        let Some(directory) = sources[*root].path.parent().map(|path| path.to_path_buf()) else {
            continue;
        };
        let mut imported = std::collections::BTreeSet::new();
        for index in members.iter().copied() {
            let Some(program) = programs_by_source.get(&index) else {
                continue;
            };
            for import in &program.imports {
                if let Some(text) = crate::stdlib::source(&import.path) {
                    imported.insert((import.path[1].clone(), text));
                }
            }
        }
        for (module, text) in imported {
            let index = sources.len();
            sources.push(SourceFile {
                path: crate::stdlib::virtual_path(&directory, &module),
                text: text.to_owned(),
            });
            members.insert(index);
        }
    }
}

/// 把源文件按项目分组：每个文件属于离它最近的 `main.mcl` 祖先；没有祖先时
/// 自己就是单文件项目的入口。
fn project_groups(sources: &[SourceFile]) -> Vec<(usize, HashSet<usize>)> {
    let mut entries = HashMap::new();
    for (index, source) in sources.iter().enumerate() {
        if is_main_module(&source.path)
            && let Some(directory) = source.path.parent()
        {
            entries.entry(directory).or_insert(index);
        }
    }
    let mut groups: BTreeMap<usize, HashSet<usize>> = BTreeMap::new();
    for (index, source) in sources.iter().enumerate() {
        let mut root = index;
        let mut directory = source.path.parent();
        while let Some(current) = directory {
            if let Some(candidate) = entries.get(current) {
                root = *candidate;
                break;
            }
            directory = current.parent();
        }
        groups.entry(root).or_default().insert(index);
    }
    groups.into_iter().collect()
}

fn is_main_module(path: &std::path::Path) -> bool {
    path.file_name()
        .is_some_and(|name| name.to_string_lossy() == "main.mcl")
}

/// 按源文件顺序解析所有文件，返回解析成功的程序与全部词法/语法诊断。
pub(crate) fn parse_all(sources: &[SourceFile]) -> (Vec<(usize, ast::Program)>, Vec<Diagnostic>) {
    parse_from(sources, 0)
}

fn parse_from(
    sources: &[SourceFile],
    start: usize,
) -> (Vec<(usize, ast::Program)>, Vec<Diagnostic>) {
    let mut programs = Vec::new();
    let mut diagnostics = Vec::new();
    for (source_id, source) in sources.iter().enumerate().skip(start) {
        match lex(&source.text, source_id) {
            Ok(tokens) => match parse(tokens) {
                Ok(program) => programs.push((source_id, program)),
                Err(mut errors) => diagnostics.append(&mut errors),
            },
            Err(mut errors) => diagnostics.append(&mut errors),
        }
    }
    (programs, diagnostics)
}

fn collect_symbols(sources: &[SourceFile], programs: &[(usize, ast::Program)]) -> Vec<Symbol> {
    let mut symbols = Vec::new();
    for (source_id, program) in programs {
        let Some(source) = sources.get(*source_id) else {
            continue;
        };
        let path = &source.path;
        for score in &program.scores {
            symbols.push(Symbol {
                name: score.name.clone(),
                kind: SymbolKind::Score,
                path: path.clone(),
                name_span: score.name_span,
                scope: None,
                detail: format!("score {} = {}", score.name, score.initial),
            });
        }
        for objective in &program.objectives {
            symbols.push(Symbol {
                name: objective.name.clone(),
                kind: SymbolKind::Objective,
                path: path.clone(),
                name_span: objective.name_span,
                scope: None,
                detail: format!("objective {}", objective.name),
            });
        }
        for query in &program.queries {
            symbols.push(Symbol {
                name: query.name.clone(),
                kind: SymbolKind::Query,
                path: path.clone(),
                name_span: query.name_span,
                scope: None,
                detail: format!("query {} = entity({:?})", query.name, query.entity_type),
            });
        }
        for item in &program.item_stacks {
            symbols.push(Symbol {
                name: item.name.clone(),
                kind: SymbolKind::ItemStack,
                path: path.clone(),
                name_span: item.name_span,
                scope: None,
                detail: format!("item {} = item_stack({:?})", item.name, item.item_id),
            });
        }
        for storage in &program.storages {
            symbols.push(Symbol {
                name: storage.name.clone(),
                kind: SymbolKind::Storage,
                path: path.clone(),
                name_span: storage.name_span,
                scope: None,
                detail: format!(
                    "storage {} = item_list({:?}, {:?})",
                    storage.name, storage.storage_id, storage.path
                ),
            });
        }
        for slot in &program.data_slots {
            symbols.push(Symbol {
                name: slot.name.clone(),
                kind: SymbolKind::DataSlot,
                path: path.clone(),
                name_span: slot.name_span,
                scope: None,
                detail: format!(
                    "data_slot {} = {:?}(\"{}\")",
                    slot.name, slot.kind, slot.key
                ),
            });
        }
        for resource in &program.resources {
            symbols.push(Symbol {
                name: resource.name.clone(),
                kind: SymbolKind::Resource,
                path: path.clone(),
                name_span: resource.name_span,
                scope: None,
                detail: format!("resource {} {}", resource.kind, resource.name),
            });
        }
        for advancement in &program.advancements {
            symbols.push(Symbol {
                name: advancement.name.clone(),
                kind: SymbolKind::Advancement,
                path: path.clone(),
                name_span: advancement.name_span,
                scope: None,
                detail: format!(
                    "advancement {}（{} 条准则）",
                    advancement.name,
                    advancement.criteria.len()
                ),
            });
        }
        for tag in &program.function_tags {
            symbols.push(Symbol {
                name: tag.name.clone(),
                kind: SymbolKind::FunctionTag,
                path: path.clone(),
                name_span: tag.name_span,
                scope: None,
                detail: format!("fn_tag {}", tag.name),
            });
        }
        for function in &program.functions {
            symbols.push(Symbol {
                name: function.name.clone(),
                kind: SymbolKind::Function,
                path: path.clone(),
                name_span: function.name_span,
                scope: None,
                detail: function_detail(function),
            });
            for parameter in &function.parameters {
                symbols.push(Symbol {
                    name: parameter.name.clone(),
                    kind: SymbolKind::Parameter,
                    path: path.clone(),
                    name_span: parameter.span,
                    scope: Some(function.span),
                    detail: format!("fn {} 的参数", function.name),
                });
            }
            collect_locals(path, function, &function.body, &mut symbols);
        }
    }
    symbols
}

fn function_detail(function: &ast::Function) -> String {
    let parameters = function
        .parameters
        .iter()
        .map(|parameter| parameter.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let returns = if function.returns_score {
        " -> score"
    } else {
        ""
    };
    format!("fn {}({parameters}){returns}", function.name)
}

/// `let` 局部变量只在其所属函数体内可见，因此只登记名称与可见范围。
fn collect_locals(
    path: &PathBuf,
    function: &ast::Function,
    statements: &[ast::Statement],
    symbols: &mut Vec<Symbol>,
) {
    for statement in statements {
        match &statement.kind {
            ast::StatementKind::Let {
                name, name_span, ..
            } => symbols.push(Symbol {
                name: name.clone(),
                kind: SymbolKind::Local,
                path: path.clone(),
                name_span: *name_span,
                scope: Some(function.span),
                detail: format!("let {name}"),
            }),
            ast::StatementKind::For {
                variable,
                variable_span,
                body,
                ..
            } => {
                symbols.push(Symbol {
                    name: variable.clone(),
                    kind: SymbolKind::Local,
                    path: path.clone(),
                    name_span: *variable_span,
                    scope: Some(function.span),
                    detail: format!("for {variable}"),
                });
                collect_locals(path, function, body, symbols);
            }
            ast::StatementKind::Each { body, .. }
            | ast::StatementKind::InDimension { body, .. }
            | ast::StatementKind::Spawn { body, .. }
            | ast::StatementKind::Execute { body, .. }
            | ast::StatementKind::While { body, .. } => {
                collect_locals(path, function, body, symbols);
            }
            ast::StatementKind::If {
                then_body,
                else_body,
                ..
            } => {
                collect_locals(path, function, then_body, symbols);
                collect_locals(path, function, else_body, symbols);
            }
            _ => {}
        }
    }
}
