mod analysis;
mod archive;
mod ast;
mod compiler;
mod diagnostic;
mod lexer;
mod lsp;
mod modules;
mod name_walk;
mod parser;
mod stdlib;
pub mod version;

use std::collections::{BTreeSet, HashMap, VecDeque};
use std::fs;
use std::path::{Component, Path, PathBuf};

use analysis::parse_all;
use compiler::{CompileOptions, CompiledPack, compile};
use diagnostic::Diagnostic;

pub use analysis::{
    FileDiagnostic, ProjectAnalysis, SourceFile, Span, Symbol, SymbolKind, analyze,
};
pub use lsp::serve;

pub struct BuildOptions {
    pub description: String,
    pub deny_raw: bool,
}

impl Default for BuildOptions {
    fn default() -> Self {
        Self {
            description: "Generated by mclang".into(),
            deny_raw: false,
        }
    }
}

#[derive(Debug)]
pub struct BuildResult {
    pub output: PathBuf,
    pub file_count: usize,
}

#[derive(Debug)]
pub struct CheckSummary {
    pub functions: usize,
    pub scores: usize,
    pub objectives: usize,
    pub queries: usize,
    pub item_stacks: usize,
    pub storages: usize,
    pub data_slots: usize,
    pub resources: usize,
    pub advancements: usize,
    pub function_tags: usize,
    pub raw_statements: usize,
}

pub fn check_file(source_path: &Path) -> Result<CheckSummary, String> {
    let loaded = read_project(source_path)?;
    let mut program = frontend(&loaded)?;
    compile(
        &mut program,
        &CompileOptions {
            description: "Generated by mclang".into(),
        },
    )
    .map_err(|diagnostics| render(&loaded.sources, diagnostics))?;
    load_binary_assets(&loaded.directory, &program.namespace)?;
    load_pack_metadata(&loaded.directory, None)?;
    Ok(CheckSummary {
        functions: program.functions.len(),
        scores: program.scores.len(),
        objectives: program.objectives.len(),
        queries: program.queries.len(),
        item_stacks: program.item_stacks.len(),
        storages: program.storages.len(),
        data_slots: program.data_slots.len(),
        resources: program.resources.len(),
        advancements: program.advancements.len(),
        function_tags: program.function_tags.len(),
        raw_statements: raw_statement_count(&program.functions),
    })
}

pub fn build_file(
    source_path: &Path,
    output: &Path,
    options: &BuildOptions,
) -> Result<BuildResult, String> {
    let pack = prepare_pack(source_path, options)?;
    write_pack(output, &pack)?;
    Ok(BuildResult {
        output: output.to_path_buf(),
        file_count: pack.files.len() + pack.binary_files.len(),
    })
}

/// Build a single-file ZIP rooted at `pack.mcmeta` and `data/`.
/// Directory-build bookkeeping (`.mclang-manifest`) is not archived.
pub fn build_zip_file(
    source_path: &Path,
    output: &Path,
    options: &BuildOptions,
) -> Result<BuildResult, String> {
    let pack = prepare_pack(source_path, options)?;
    archive::write_pack_zip(output, &pack)?;
    Ok(BuildResult {
        output: output.to_path_buf(),
        file_count: pack.files.len() + pack.binary_files.len(),
    })
}

fn prepare_pack(source_path: &Path, options: &BuildOptions) -> Result<CompiledPack, String> {
    let loaded = read_project(source_path)?;
    let mut program = frontend(&loaded)?;
    let raw_statements = raw_statement_count(&program.functions);
    if options.deny_raw && raw_statements > 0 {
        return Err(format!(
            "严格模式拒绝构建：项目包含 {raw_statements} 条底层语句或不安全宏（run/execute/return run/运行期 with/nbt 宏片段）"
        ));
    }
    let mut pack = compile(
        &mut program,
        &CompileOptions {
            description: options.description.clone(),
        },
    )
    .map_err(|diagnostics| render(&loaded.sources, diagnostics))?;
    pack.binary_files = load_binary_assets(&loaded.directory, &program.namespace)?;
    if let Some(metadata) = load_pack_metadata(&loaded.directory, Some(&options.description))? {
        pack.files.insert(PathBuf::from("pack.mcmeta"), metadata);
    }
    Ok(pack)
}

fn raw_statement_count(functions: &[ast::Function]) -> usize {
    functions
        .iter()
        .map(|function| {
            raw_count_in_block(&function.body)
                + usize::from(
                    function.macro_signature.as_ref().is_some_and(|s| {
                        s.parameters.iter().any(|p| p.kind == ast::MacroType::Nbt)
                    }),
                )
        })
        .sum()
}

fn raw_count_in_block(statements: &[ast::Statement]) -> usize {
    statements
        .iter()
        .map(|statement| match &statement.kind {
            ast::StatementKind::MacroCall { arguments, .. } => {
                usize::from(matches!(arguments, ast::MacroArguments::With { .. }))
            }
            ast::StatementKind::CoreCommand(_) | ast::StatementKind::EntityCommand(_) => 0,
            ast::StatementKind::Run(_) => 1,
            ast::StatementKind::Return(ast::ReturnKind::Run(_)) => 1,
            ast::StatementKind::Return(ast::ReturnKind::Command(command)) => {
                raw_count_in_block(std::slice::from_ref(command.as_ref()))
            }
            ast::StatementKind::Execute {
                clauses: ast::ExecuteClauses::Raw(_),
                body,
            } => 1 + raw_count_in_block(body),
            ast::StatementKind::Execute {
                clauses: ast::ExecuteClauses::Structured(_),
                body,
            } => raw_count_in_block(body),
            ast::StatementKind::Each { body, .. }
            | ast::StatementKind::InDimension { body, .. }
            | ast::StatementKind::Spawn { body, .. }
            | ast::StatementKind::While { body, .. }
            | ast::StatementKind::For { body, .. } => raw_count_in_block(body),
            ast::StatementKind::Break | ast::StatementKind::Continue => 0,
            ast::StatementKind::If {
                then_body,
                else_body,
                ..
            } => raw_count_in_block(then_body) + raw_count_in_block(else_body),
            ast::StatementKind::Give { .. }
            | ast::StatementKind::EffectGive { .. }
            | ast::StatementKind::EffectClear { .. }
            | ast::StatementKind::XpChange { .. }
            | ast::StatementKind::StopwatchAction { .. }
            | ast::StatementKind::ClearInventory { .. }
            | ast::StatementKind::SetBlock { .. }
            | ast::StatementKind::Fill { .. }
            | ast::StatementKind::FillBiome { .. }
            | ast::StatementKind::Clone { .. }
            | ast::StatementKind::PlaceFeature { .. }
            | ast::StatementKind::PlaceJigsaw { .. }
            | ast::StatementKind::PlaceStructure { .. }
            | ast::StatementKind::PlaceTemplate { .. }
            | ast::StatementKind::ForceLoad(_)
            | ast::StatementKind::TimeAction { .. }
            | ast::StatementKind::Weather { .. }
            | ast::StatementKind::GameRuleSet { .. }
            | ast::StatementKind::WorldBorder(_)
            | ast::StatementKind::Locate { .. }
            | ast::StatementKind::SelfAction(_)
            | ast::StatementKind::Message { .. }
            | ast::StatementKind::PlaySound { .. }
            | ast::StatementKind::UiCommand(_)
            | ast::StatementKind::Call { .. }
            | ast::StatementKind::Let { .. }
            | ast::StatementKind::Schedule { .. }
            | ast::StatementKind::ScheduleClear { .. }
            | ast::StatementKind::Assign { .. }
            | ast::StatementKind::ScoreSet { .. }
            | ast::StatementKind::ScoreReset { .. }
            | ast::StatementKind::ScoreboardEnable { .. }
            | ast::StatementKind::ScoreboardOperation { .. }
            | ast::StatementKind::ScoreboardDisplay { .. }
            | ast::StatementKind::ScoreboardCommand(_)
            | ast::StatementKind::DataMerge { .. }
            | ast::StatementKind::DataRemove { .. }
            | ast::StatementKind::DataModify { .. }
            | ast::StatementKind::ItemAction { .. }
            | ast::StatementKind::Teleport { .. }
            | ast::StatementKind::NbtMerge { .. }
            | ast::StatementKind::AdvancementAction { .. }
            | ast::StatementKind::Return(_) => 0,
        })
        .sum()
}

/// 从磁盘加载的项目：可达模块的源文件与入口在其中的下标。
struct LoadedSources {
    sources: Vec<SourceFile>,
    root: usize,
    directory: PathBuf,
}

/// 加载项目：入口是 `main.mcl`（目录输入）或给定文件（文件输入），
/// 其余模块沿 `import` 边按需读取；不可达的 `.mcl` 文件不参与编译。
fn read_project(path: &Path) -> Result<LoadedSources, String> {
    let metadata =
        fs::metadata(path).map_err(|error| format!("无法访问 {}：{error}", path.display()))?;
    let (entry, directory) = if metadata.is_file() {
        let directory = path
            .parent()
            .map_or_else(|| PathBuf::from("."), Path::to_path_buf);
        (path.to_path_buf(), directory)
    } else if metadata.is_dir() {
        let entry = path.join("main.mcl");
        if !entry.is_file() {
            return Err(format!(
                "目录 {} 缺少入口模块 main.mcl：项目根目录必须放入口模块，\
                 其余 .mcl 文件由入口用 `import 模块::路径;` 引入",
                path.display()
            ));
        }
        (entry, path.to_path_buf())
    } else {
        return Err(format!("输入 {} 不是普通文件或目录", path.display()));
    };

    let mut sources: Vec<SourceFile> = Vec::new();
    let mut indices: HashMap<PathBuf, usize> = HashMap::new();
    let mut queue: VecDeque<PathBuf> = VecDeque::new();
    let root = push_source(&mut sources, &mut indices, &entry)?;
    queue.push_back(entry);

    while let Some(file) = queue.pop_front() {
        let index = indices[&file];
        let text = &sources[index].text;
        // 语法错误会在统一的解析阶段报告；这里拿不到导入表就停止展开该分支。
        let imports = match lexer::lex(text, index) {
            Ok(tokens) => parser::parse(tokens).map(|program| program.imports).ok(),
            Err(_) => None,
        };
        let Some(imports) = imports else {
            continue;
        };
        for import in imports {
            if import.path.first().is_some_and(|segment| segment == "std") {
                if let Some(text) = stdlib::source(&import.path) {
                    let target = stdlib::virtual_path(&directory, &import.path[1]);
                    if !indices.contains_key(&target) {
                        let target_index = sources.len();
                        indices.insert(target.clone(), target_index);
                        sources.push(SourceFile {
                            path: target.clone(),
                            text: text.to_owned(),
                        });
                        queue.push_back(target);
                    }
                }
                continue;
            }
            let Some(target) = module_file(&directory, &import.path) else {
                continue;
            };
            if indices.contains_key(&target) {
                continue;
            }
            let target_index = push_source(&mut sources, &mut indices, &target)?;
            sources[target_index].path = target.clone();
            queue.push_back(target);
        }
    }

    Ok(LoadedSources {
        sources,
        root,
        directory,
    })
}

fn push_source(
    sources: &mut Vec<SourceFile>,
    indices: &mut HashMap<PathBuf, usize>,
    path: &Path,
) -> Result<usize, String> {
    let text = fs::read_to_string(path)
        .map_err(|error| format!("无法读取 {}：{error}", path.display()))?;
    let index = sources.len();
    indices.insert(path.to_path_buf(), index);
    sources.push(SourceFile {
        path: path.to_path_buf(),
        text,
    });
    Ok(index)
}

/// `import a::b;` 对应的文件：`<根目录>/a/b.mcl` 或 `<根目录>/a/b/mod.mcl`。
fn module_file(directory: &Path, segments: &[String]) -> Option<PathBuf> {
    let mut base = directory.to_path_buf();
    for segment in segments {
        base.push(segment);
    }
    let file = base.with_extension("mcl");
    if file.is_file() {
        return Some(file);
    }
    let directory_module = base.join("mod.mcl");
    directory_module.is_file().then_some(directory_module)
}

fn frontend(loaded: &LoadedSources) -> Result<ast::Program, String> {
    let (programs, diagnostics) = parse_all(&loaded.sources);
    if !diagnostics.is_empty() {
        return Err(render(&loaded.sources, diagnostics));
    }
    modules::resolve(programs, &loaded.sources, loaded.root)
        .map_err(|diagnostics| render(&loaded.sources, diagnostics))
}

/// 递归收集目录下的全部 `.mcl` 源文件（语言服务器用于发现工作区文件）。
pub(crate) fn discover_sources(directory: &Path, paths: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = fs::read_dir(directory)
        .map_err(|error| format!("无法读取目录 {}：{error}", directory.display()))?;
    for entry in entries {
        let entry = entry.map_err(|error| format!("无法读取目录项：{error}"))?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|error| format!("无法读取 {} 的类型：{error}", path.display()))?;
        if file_type.is_dir() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if !name.starts_with('.')
                && !matches!(name.as_ref(), "target" | "build" | "node_modules")
            {
                discover_sources(&path, paths)?;
            }
        } else if file_type.is_file()
            && path.extension().and_then(|extension| extension.to_str()) == Some("mcl")
        {
            paths.push(path);
        }
    }
    Ok(())
}

fn render(sources: &[SourceFile], diagnostics: Vec<Diagnostic>) -> String {
    diagnostics
        .into_iter()
        .map(|diagnostic| {
            let source = &sources[diagnostic.span.source];
            diagnostic.render(&source.path, &source.text)
        })
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn write_pack(output: &Path, pack: &CompiledPack) -> Result<(), String> {
    fs::create_dir_all(output)
        .map_err(|error| format!("无法创建输出目录 {}：{error}", output.display()))?;
    let manifest_path = output.join(".mclang-manifest");
    remove_old_outputs(output, &manifest_path)?;

    // 新构建本身不会产生空目录：目录只作为文件的父路径创建。空目录来自重建时
    // 被清单删掉的旧文件，所以无论本次写入是否完整，最后都清理一次 data/ 下的
    // 空目录，避免函数改名、模块删除后把空壳留在输出里。
    let files_result = write_files(output, pack);
    let prune_result = remove_empty_directories(&output.join("data"));
    files_result?;
    prune_result?;

    let manifest = pack
        .files
        .keys()
        .chain(pack.binary_files.keys())
        .map(|path| path.to_string_lossy().replace('\\', "/"))
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";
    fs::write(&manifest_path, manifest)
        .map_err(|error| format!("无法写入 {}：{error}", manifest_path.display()))
}

fn write_files(output: &Path, pack: &CompiledPack) -> Result<(), String> {
    for (relative, contents) in &pack.files {
        let path = output.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("无法创建目录 {}：{error}", parent.display()))?;
        }
        fs::write(&path, contents)
            .map_err(|error| format!("无法写入 {}：{error}", path.display()))?;
    }
    for (relative, contents) in &pack.binary_files {
        let path = output.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("无法创建目录 {}：{error}", parent.display()))?;
        }
        fs::write(&path, contents)
            .map_err(|error| format!("无法写入 {}：{error}", path.display()))?;
    }
    Ok(())
}

/// Copy project assets/structure/**/*.nbt into the namespace's data directory.
/// Symlinks are skipped, so every copied file stays inside the project tree.
fn load_binary_assets(
    directory: &Path,
    namespace: &str,
) -> Result<std::collections::BTreeMap<PathBuf, Vec<u8>>, String> {
    let mut files = load_structure_assets(directory, namespace)?;
    load_pack_icon(directory, &mut files)?;
    load_overlay_assets(directory, &mut files)?;
    Ok(files)
}

fn load_structure_assets(
    directory: &Path,
    namespace: &str,
) -> Result<std::collections::BTreeMap<PathBuf, Vec<u8>>, String> {
    let root = directory.join("assets/structure");
    let mut files = std::collections::BTreeMap::new();
    if root.is_dir() {
        for path in [directory.join("assets"), root.clone()] {
            if fs::symlink_metadata(&path)
                .map_err(|error| format!("无法读取 {}：{error}", path.display()))?
                .file_type()
                .is_symlink()
            {
                return Err(format!("结构资源目录 {} 不能是符号链接", path.display()));
            }
        }
        let mut pending = vec![root.clone()];
        while let Some(directory) = pending.pop() {
            for entry in fs::read_dir(&directory)
                .map_err(|error| format!("无法读取结构资源目录 {}：{error}", directory.display()))?
            {
                let entry = entry.map_err(|error| format!("无法读取结构资源目录项：{error}"))?;
                let file_type = entry.file_type().map_err(|error| {
                    format!("无法读取 {} 的类型：{error}", entry.path().display())
                })?;
                if file_type.is_dir() {
                    pending.push(entry.path());
                } else if file_type.is_file()
                    && entry.path().extension().and_then(|ext| ext.to_str()) == Some("nbt")
                {
                    let relative = entry
                        .path()
                        .strip_prefix(&root)
                        .expect("asset path is inside structure root")
                        .to_path_buf();
                    let name = relative
                        .with_extension("")
                        .to_string_lossy()
                        .replace('\\', "/");
                    if !compiler::valid_resource_path(&name) {
                        return Err(format!("结构资源名称 `{name}` 不是有效的资源路径"));
                    }
                    let contents = fs::read(entry.path())
                        .map_err(|error| format!("无法读取 {}：{error}", entry.path().display()))?;
                    if !contents.starts_with(&[0x1f, 0x8b]) {
                        return Err(format!("结构资源 `{name}` 必须是 gzip 压缩的 NBT 文件"));
                    }
                    files.insert(
                        PathBuf::from("data")
                            .join(namespace)
                            .join("structure")
                            .join(relative),
                        contents,
                    );
                }
            }
        }
    }

    Ok(files)
}

fn load_pack_icon(
    directory: &Path,
    files: &mut std::collections::BTreeMap<PathBuf, Vec<u8>>,
) -> Result<(), String> {
    let icon = directory.join("assets/pack.png");
    if !icon.exists() {
        return Ok(());
    }
    let metadata = fs::symlink_metadata(&icon)
        .map_err(|error| format!("无法读取 {}：{error}", icon.display()))?;
    if !metadata.is_file() || metadata.file_type().is_symlink() {
        return Err(format!("数据包图标 {} 必须是普通文件", icon.display()));
    }
    let contents =
        fs::read(&icon).map_err(|error| format!("无法读取 {}：{error}", icon.display()))?;
    if !contents.starts_with(b"\x89PNG\r\n\x1a\n") {
        return Err(format!("数据包图标 {} 不是有效的 PNG 文件", icon.display()));
    }
    files.insert(PathBuf::from("pack.png"), contents);
    Ok(())
}

/// Copy `assets/overlays/high/data/...` to `high/data/...`. Symlink rejection
/// keeps every copied file inside the project tree.
fn load_overlay_assets(
    directory: &Path,
    files: &mut std::collections::BTreeMap<PathBuf, Vec<u8>>,
) -> Result<(), String> {
    let overlays = directory.join("assets/overlays");
    if !overlays.is_dir() {
        return Ok(());
    }
    if fs::symlink_metadata(&overlays)
        .map_err(|error| format!("无法读取 {}：{error}", overlays.display()))?
        .file_type()
        .is_symlink()
    {
        return Err(format!(
            "overlay 资源目录 {} 不能是符号链接",
            overlays.display()
        ));
    }
    let mut pending = vec![overlays.clone()];
    while let Some(current) = pending.pop() {
        for entry in fs::read_dir(&current)
            .map_err(|error| format!("无法读取 overlay 目录 {}：{error}", current.display()))?
        {
            let entry = entry.map_err(|error| format!("无法读取 overlay 目录项：{error}"))?;
            let file_type = entry
                .file_type()
                .map_err(|error| format!("无法读取 {} 的类型：{error}", entry.path().display()))?;
            if file_type.is_symlink() {
                return Err(format!(
                    "overlay 资源 {} 不能是符号链接",
                    entry.path().display()
                ));
            }
            if file_type.is_dir() {
                pending.push(entry.path());
            } else if file_type.is_file() {
                let relative = entry
                    .path()
                    .strip_prefix(&overlays)
                    .expect("overlay asset is inside its root")
                    .to_path_buf();
                if relative.components().count() < 2 {
                    return Err(format!(
                        "overlay 文件 {} 必须位于 assets/overlays/<目录>/ 下",
                        entry.path().display()
                    ));
                }
                let contents = fs::read(entry.path()).map_err(|error| {
                    format!("无法读取 overlay 资源 {}：{error}", entry.path().display())
                })?;
                files.insert(relative, contents);
            }
        }
    }
    Ok(())
}

/// Load the optional complete metadata template. The CLI description always
/// overrides its description after known fields have been validated.
fn load_pack_metadata(
    directory: &Path,
    description: Option<&str>,
) -> Result<Option<String>, String> {
    let path = directory.join("assets/pack.mcmeta");
    if !path.exists() {
        if directory.join("assets/overlays").is_dir() {
            return Err(
                "assets/overlays 需要在 assets/pack.mcmeta 中声明 overlays.entries".to_owned(),
            );
        }
        return Ok(None);
    }
    let metadata = fs::symlink_metadata(&path)
        .map_err(|error| format!("无法读取 {}：{error}", path.display()))?;
    if !metadata.is_file() || metadata.file_type().is_symlink() {
        return Err(format!("数据包元数据 {} 必须是普通文件", path.display()));
    }
    let source = fs::read_to_string(&path)
        .map_err(|error| format!("无法读取 {}：{error}", path.display()))?;
    let mut value: serde_json::Value = serde_json::from_str(&source)
        .map_err(|error| format!("{} 不是有效 JSON：{error}", path.display()))?;
    validate_pack_metadata(&value).map_err(|error| format!("{}：{error}", path.display()))?;
    validate_overlay_layout(directory, &value)?;
    if let Some(description) = description {
        value["pack"]["description"] = serde_json::Value::String(description.to_owned());
    }
    Ok(Some(
        serde_json::to_string_pretty(&value).expect("parsed JSON can be serialized") + "\n",
    ))
}

fn validate_overlay_layout(directory: &Path, metadata: &serde_json::Value) -> Result<(), String> {
    let declared = metadata["overlays"]["entries"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|entry| entry["directory"].as_str())
        .collect::<BTreeSet<_>>();
    let root = directory.join("assets/overlays");
    if !root.is_dir() {
        if let Some(missing) = declared.first() {
            return Err(format!(
                "pack.mcmeta 声明了 overlay `{missing}`，但缺少 assets/overlays/{missing}"
            ));
        }
        return Ok(());
    }
    for name in &declared {
        if !root.join(name).is_dir() {
            return Err(format!(
                "pack.mcmeta 声明了 overlay `{name}`，但缺少 assets/overlays/{name}"
            ));
        }
    }
    for entry in
        fs::read_dir(&root).map_err(|error| format!("无法读取 {}：{error}", root.display()))?
    {
        let entry = entry.map_err(|error| format!("无法读取 overlay 目录项：{error}"))?;
        if entry
            .file_type()
            .map_err(|error| format!("无法读取 {} 的类型：{error}", entry.path().display()))?
            .is_dir()
        {
            let name = entry.file_name().to_string_lossy().into_owned();
            if !declared.contains(name.as_str()) {
                return Err(format!(
                    "assets/overlays/{name} 未在 pack.mcmeta 的 overlays.entries 中声明"
                ));
            }
        }
    }
    Ok(())
}

fn validate_pack_metadata(value: &serde_json::Value) -> Result<(), String> {
    let root = value
        .as_object()
        .ok_or_else(|| "根值必须是 JSON 对象".to_owned())?;
    let pack = root
        .get("pack")
        .and_then(serde_json::Value::as_object)
        .ok_or_else(|| "缺少 pack 对象".to_owned())?;
    if !pack
        .get("description")
        .is_some_and(|value| value.is_string() || value.is_object() || value.is_array())
    {
        return Err("pack.description 必须是文本或文本组件".to_owned());
    }
    for field in ["min_format", "max_format"] {
        if let Some(value) = pack.get(field)
            && !valid_pack_format(value)
        {
            return Err(format!("pack.{field} 必须是非负整数或 [主版本, 次版本]"));
        }
    }
    if pack.contains_key("min_format") != pack.contains_key("max_format") {
        return Err("pack.min_format 与 pack.max_format 必须同时声明".to_owned());
    }
    if let Some(value) = pack.get("pack_format")
        && !valid_pack_format(value)
    {
        return Err("pack.pack_format 必须是非负整数或 [主版本, 次版本]".to_owned());
    }
    if !pack.contains_key("pack_format") && !pack.contains_key("min_format") {
        return Err("pack 需要 pack_format，或同时声明 min_format 与 max_format".to_owned());
    }
    if let Some(value) = pack.get("supported_formats")
        && !valid_supported_formats(value)
    {
        return Err("pack.supported_formats 格式无效".to_owned());
    }

    if let Some(overlays) = root.get("overlays") {
        let entries = overlays
            .get("entries")
            .and_then(serde_json::Value::as_array)
            .ok_or_else(|| "overlays.entries 必须是数组".to_owned())?;
        for (index, entry) in entries.iter().enumerate() {
            let entry = entry
                .as_object()
                .ok_or_else(|| format!("overlays.entries 第 {} 项必须是对象", index + 1))?;
            if !entry.get("formats").is_some_and(valid_supported_formats) {
                return Err(format!(
                    "overlays.entries 第 {} 项的 formats 无效",
                    index + 1
                ));
            }
            let directory = entry.get("directory").and_then(serde_json::Value::as_str);
            if !directory.is_some_and(valid_relative_asset_directory) {
                return Err(format!(
                    "overlays.entries 第 {} 项的 directory 无效",
                    index + 1
                ));
            }
        }
    }
    if let Some(filter) = root.get("filter") {
        let blocks = filter
            .get("block")
            .and_then(serde_json::Value::as_array)
            .ok_or_else(|| "filter.block 必须是数组".to_owned())?;
        for (index, block) in blocks.iter().enumerate() {
            let block = block
                .as_object()
                .ok_or_else(|| format!("filter.block 第 {} 项必须是对象", index + 1))?;
            if !block.contains_key("namespace") && !block.contains_key("path") {
                return Err(format!(
                    "filter.block 第 {} 项至少需要 namespace 或 path",
                    index + 1
                ));
            }
            for field in ["namespace", "path"] {
                if block.get(field).is_some_and(|value| !value.is_string()) {
                    return Err(format!(
                        "filter.block 第 {} 项的 {field} 必须是字符串",
                        index + 1
                    ));
                }
            }
        }
    }
    if let Some(features) = root.get("features") {
        let enabled = features
            .get("enabled")
            .and_then(serde_json::Value::as_array)
            .ok_or_else(|| "features.enabled 必须是数组".to_owned())?;
        if !enabled
            .iter()
            .all(|entry| entry.as_str().is_some_and(valid_resource_location_text))
        {
            return Err("features.enabled 必须只包含有效资源位置".to_owned());
        }
    }
    Ok(())
}

fn valid_pack_format(value: &serde_json::Value) -> bool {
    value.as_u64().is_some()
        || value.as_array().is_some_and(|parts| {
            parts.len() == 2 && parts.iter().all(|part| part.as_u64().is_some())
        })
}

fn valid_supported_formats(value: &serde_json::Value) -> bool {
    valid_pack_format(value)
        || value
            .as_array()
            .is_some_and(|range| range.len() == 2 && range.iter().all(valid_pack_format))
        || value.as_object().is_some_and(|range| {
            range.get("min_inclusive").is_some_and(valid_pack_format)
                && range.get("max_inclusive").is_some_and(valid_pack_format)
        })
}

fn valid_relative_asset_directory(value: &str) -> bool {
    !value.is_empty()
        && !Path::new(value).is_absolute()
        && !value.contains('\\')
        && Path::new(value)
            .components()
            .all(|component| matches!(component, Component::Normal(_)))
}

fn valid_resource_location_text(value: &str) -> bool {
    let (namespace, path) = value
        .split_once(':')
        .map_or(("minecraft", value), |(namespace, path)| (namespace, path));
    !namespace.is_empty()
        && namespace.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || b"_.-".contains(&byte)
        })
        && compiler::valid_resource_path(path)
}

/// 自底向上删除目录树里不再包含任何文件的空目录。
///
/// 编译器的产物都写在 `data/` 下，调用方也只对该子树调用本函数；只删空目录，
/// 有内容的目录原样保留，因此不会影响清单之外的文件。符号链接不会被当作目录
/// 进入，未创建的目录直接视为干净。
fn remove_empty_directories(directory: &Path) -> Result<(), String> {
    let entries = match fs::read_dir(directory) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(format!("无法读取目录 {}：{error}", directory.display())),
    };
    for entry in entries {
        let entry = entry.map_err(|error| format!("无法读取目录项：{error}"))?;
        let file_type = entry
            .file_type()
            .map_err(|error| format!("无法读取 {} 的类型：{error}", entry.path().display()))?;
        if file_type.is_dir() {
            remove_empty_directories(&entry.path())?;
        }
    }
    // 子目录可能刚被清空，重新检查一次再决定是否删除自己。
    let empty = fs::read_dir(directory)
        .map_err(|error| format!("无法读取目录 {}：{error}", directory.display()))?
        .next()
        .is_none();
    if !empty {
        return Ok(());
    }
    fs::remove_dir(directory)
        .map_err(|error| format!("无法删除空目录 {}：{error}", directory.display()))
}

fn remove_old_outputs(output: &Path, manifest: &Path) -> Result<(), String> {
    let Ok(contents) = fs::read_to_string(manifest) else {
        return Ok(());
    };
    let mut paths = BTreeSet::new();
    for line in contents.lines() {
        let relative = Path::new(line);
        if line.is_empty()
            || relative.is_absolute()
            || relative
                .components()
                .any(|part| !matches!(part, Component::Normal(_)))
        {
            return Err(format!("拒绝使用损坏的构建清单 {}", manifest.display()));
        }
        paths.insert(relative.to_path_buf());
    }
    for relative in paths {
        let path = output.join(relative);
        match fs::remove_file(&path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(format!("无法清理旧输出 {}：{error}", path.display())),
        }
    }
    Ok(())
}
