mod ast;
mod compiler;
mod diagnostic;
mod lexer;
mod parser;

use std::collections::BTreeSet;
use std::fs;
use std::path::{Component, Path, PathBuf};

use compiler::{CompiledPack, compile};
use diagnostic::Diagnostic;
use lexer::lex;
use parser::parse;

pub struct BuildOptions {
    pub description: String,
    pub deny_raw: bool,
}

pub struct BuildResult {
    pub output: PathBuf,
    pub file_count: usize,
}

pub struct CheckSummary {
    pub functions: usize,
    pub scores: usize,
    pub queries: usize,
    pub item_stacks: usize,
    pub storages: usize,
    pub resources: usize,
    pub function_tags: usize,
    pub raw_statements: usize,
}

pub fn check_file(source_path: &Path) -> Result<CheckSummary, String> {
    let sources = read_sources(source_path)?;
    let program = frontend(&sources)?;
    compile(&program, "Generated by mclang")
        .map_err(|diagnostics| render(&sources, diagnostics))?;
    Ok(CheckSummary {
        functions: program.functions.len(),
        scores: program.scores.len(),
        queries: program.queries.len(),
        item_stacks: program.item_stacks.len(),
        storages: program.storages.len(),
        resources: program.resources.len(),
        function_tags: program.function_tags.len(),
        raw_statements: raw_statement_count(&program.functions),
    })
}

pub fn build_file(
    source_path: &Path,
    output: &Path,
    options: &BuildOptions,
) -> Result<BuildResult, String> {
    let sources = read_sources(source_path)?;
    let program = frontend(&sources)?;
    let raw_statements = raw_statement_count(&program.functions);
    if options.deny_raw && raw_statements > 0 {
        return Err(format!(
            "严格模式拒绝构建：项目包含 {raw_statements} 条底层 run/execute 语句"
        ));
    }
    let pack = compile(&program, &options.description)
        .map_err(|diagnostics| render(&sources, diagnostics))?;
    write_pack(output, &pack)?;
    Ok(BuildResult {
        output: output.to_path_buf(),
        file_count: pack.files.len(),
    })
}

fn raw_statement_count(functions: &[ast::Function]) -> usize {
    functions
        .iter()
        .map(|function| raw_count_in_block(&function.body))
        .sum()
}

fn raw_count_in_block(statements: &[ast::Statement]) -> usize {
    statements
        .iter()
        .map(|statement| match &statement.kind {
            ast::StatementKind::Run(_) => 1,
            ast::StatementKind::Return(ast::ReturnKind::Run(_)) => 1,
            ast::StatementKind::Execute { body, .. } => 1 + raw_count_in_block(body),
            ast::StatementKind::Each { body, .. }
            | ast::StatementKind::InDimension { body, .. }
            | ast::StatementKind::Spawn { body, .. }
            | ast::StatementKind::While { body, .. } => raw_count_in_block(body),
            ast::StatementKind::If {
                then_body,
                else_body,
                ..
            } => raw_count_in_block(then_body) + raw_count_in_block(else_body),
            ast::StatementKind::Give { .. }
            | ast::StatementKind::EffectGive { .. }
            | ast::StatementKind::EffectClear { .. }
            | ast::StatementKind::XpChange { .. }
            | ast::StatementKind::ClearInventory { .. }
            | ast::StatementKind::SelfAction(_)
            | ast::StatementKind::Message { .. }
            | ast::StatementKind::PlaySound { .. }
            | ast::StatementKind::Call { .. }
            | ast::StatementKind::Let { .. }
            | ast::StatementKind::Schedule { .. }
            | ast::StatementKind::ScheduleClear { .. }
            | ast::StatementKind::Assign { .. }
            | ast::StatementKind::Return(_) => 0,
        })
        .sum()
}

struct SourceFile {
    path: PathBuf,
    text: String,
}

fn read_sources(path: &Path) -> Result<Vec<SourceFile>, String> {
    let metadata =
        fs::metadata(path).map_err(|error| format!("无法访问 {}：{error}", path.display()))?;
    let mut paths = Vec::new();
    if metadata.is_file() {
        paths.push(path.to_path_buf());
    } else if metadata.is_dir() {
        discover_sources(path, &mut paths)?;
    } else {
        return Err(format!("输入 {} 不是普通文件或目录", path.display()));
    }
    paths.sort();
    if paths.is_empty() {
        return Err(format!("目录 {} 中没有 .mcl 源文件", path.display()));
    }

    paths
        .into_iter()
        .map(|path| {
            let text = fs::read_to_string(&path)
                .map_err(|error| format!("无法读取 {}：{error}", path.display()))?;
            Ok(SourceFile { path, text })
        })
        .collect()
}

fn discover_sources(directory: &Path, paths: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = fs::read_dir(directory)
        .map_err(|error| format!("无法读取目录 {}：{error}", directory.display()))?;
    for entry in entries {
        let entry = entry.map_err(|error| format!("无法读取目录项：{error}"))?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|error| format!("无法读取 {} 的类型：{error}", path.display()))?;
        if file_type.is_dir() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if !name.starts_with('.') && name != "target" && name != "build" {
                discover_sources(&path, paths)?;
            }
        } else if file_type.is_file()
            && path.extension().and_then(|extension| extension.to_str()) == Some("mcl")
        {
            paths.push(path);
        }
    }
    Ok(())
}

fn frontend(sources: &[SourceFile]) -> Result<ast::Program, String> {
    let mut programs = Vec::new();
    let mut diagnostics = Vec::new();
    for (source_id, source) in sources.iter().enumerate() {
        match lex(&source.text, source_id) {
            Ok(tokens) => match parse(tokens) {
                Ok(program) => programs.push(program),
                Err(mut errors) => diagnostics.append(&mut errors),
            },
            Err(mut errors) => diagnostics.append(&mut errors),
        }
    }
    if !diagnostics.is_empty() {
        return Err(render(sources, diagnostics));
    }

    let mut programs = programs.into_iter();
    let mut program = programs
        .next()
        .expect("read_sources guarantees at least one source");
    for mut other in programs {
        if other.namespace != program.namespace {
            diagnostics.push(Diagnostic::new(
                format!(
                    "项目命名空间必须一致：预期 `{}`，实际为 `{}`",
                    program.namespace, other.namespace
                ),
                other.namespace_span,
            ));
        }
        program.scores.append(&mut other.scores);
        program.queries.append(&mut other.queries);
        program.item_stacks.append(&mut other.item_stacks);
        program.storages.append(&mut other.storages);
        program.resources.append(&mut other.resources);
        program.function_tags.append(&mut other.function_tags);
        program.functions.append(&mut other.functions);
    }
    if diagnostics.is_empty() {
        Ok(program)
    } else {
        Err(render(sources, diagnostics))
    }
}

fn render(sources: &[SourceFile], diagnostics: Vec<Diagnostic>) -> String {
    diagnostics
        .into_iter()
        .map(|diagnostic| {
            let source = &sources[diagnostic.span.source];
            diagnostic.render(&source.path, &source.text)
        })
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn write_pack(output: &Path, pack: &CompiledPack) -> Result<(), String> {
    fs::create_dir_all(output)
        .map_err(|error| format!("无法创建输出目录 {}：{error}", output.display()))?;
    let manifest_path = output.join(".mclang-manifest");
    remove_old_outputs(output, &manifest_path)?;

    for (relative, contents) in &pack.files {
        let path = output.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("无法创建目录 {}：{error}", parent.display()))?;
        }
        fs::write(&path, contents)
            .map_err(|error| format!("无法写入 {}：{error}", path.display()))?;
    }

    let manifest = pack
        .files
        .keys()
        .map(|path| path.to_string_lossy().replace('\\', "/"))
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";
    fs::write(&manifest_path, manifest)
        .map_err(|error| format!("无法写入 {}：{error}", manifest_path.display()))
}

fn remove_old_outputs(output: &Path, manifest: &Path) -> Result<(), String> {
    let Ok(contents) = fs::read_to_string(manifest) else {
        return Ok(());
    };
    let mut paths = BTreeSet::new();
    for line in contents.lines() {
        let relative = Path::new(line);
        if line.is_empty()
            || relative.is_absolute()
            || relative
                .components()
                .any(|part| !matches!(part, Component::Normal(_)))
        {
            return Err(format!("拒绝使用损坏的构建清单 {}", manifest.display()));
        }
        paths.insert(relative.to_path_buf());
    }
    for relative in paths {
        let path = output.join(relative);
        match fs::remove_file(&path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(format!("无法清理旧输出 {}：{error}", path.display())),
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn rebuild_removes_stale_generated_files_and_preserves_foreign_files() {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let output =
            std::env::temp_dir().join(format!("mclang-test-{}-{nonce}", std::process::id()));
        fs::create_dir_all(&output).unwrap();
        fs::write(output.join("keep.txt"), "user file").unwrap();

        let first = CompiledPack {
            files: BTreeMap::from([(PathBuf::from("old.mcfunction"), "old".to_owned())]),
        };
        write_pack(&output, &first).unwrap();
        let second = CompiledPack {
            files: BTreeMap::from([(PathBuf::from("new.mcfunction"), "new".to_owned())]),
        };
        write_pack(&output, &second).unwrap();

        assert!(!output.join("old.mcfunction").exists());
        assert_eq!(
            fs::read_to_string(output.join("new.mcfunction")).unwrap(),
            "new"
        );
        assert_eq!(
            fs::read_to_string(output.join("keep.txt")).unwrap(),
            "user file"
        );
        fs::remove_dir_all(output).unwrap();
    }

    #[test]
    fn merges_cross_file_references_and_reports_namespace_source() {
        let sources = vec![
            SourceFile {
                path: PathBuf::from("main.mcl"),
                text: "namespace demo; query players = entity(\"minecraft:player\") {} fn main() { each(players) { self.give_item(reward); helper(); } }".to_owned(),
            },
            SourceFile {
                path: PathBuf::from("helper.mcl"),
                text: "namespace demo; item reward = item_stack(\"minecraft:emerald\") {} fn helper() {}".to_owned(),
            },
        ];
        let program = frontend(&sources).unwrap();
        assert!(compile(&program, "test").is_ok());

        let mismatched = vec![
            SourceFile {
                path: PathBuf::from("first.mcl"),
                text: "namespace first;".to_owned(),
            },
            SourceFile {
                path: PathBuf::from("second.mcl"),
                text: "namespace second;".to_owned(),
            },
        ];
        let error = frontend(&mismatched).unwrap_err();
        assert!(error.contains("second.mcl:1:11"));
    }

    #[test]
    fn counts_raw_statements_at_any_nesting_depth() {
        let sources = vec![SourceFile {
            path: PathBuf::from("strict.mcl"),
            text: r#"
                namespace strict;
                score enabled = 1;
                fn main() {
                    if enabled == 1 {
                        each(players) {
                            run "say raw";
                            execute "at @s" { run "say nested"; }
                        }
                    }
                }
                query players = entity("minecraft:player") { }
            "#
            .to_owned(),
        }];
        let program = frontend(&sources).unwrap();
        assert_eq!(raw_statement_count(&program.functions), 3);
    }

    #[test]
    fn counts_return_run_as_raw_statement() {
        let sources = vec![SourceFile {
            path: PathBuf::from("strict.mcl"),
            text: r#"
                namespace strict;
                fn structured() { return fail; }
                fn raw() -> score { return run "time query gametime"; }
            "#
            .to_owned(),
        }];
        let program = frontend(&sources).unwrap();
        assert_eq!(raw_statement_count(&program.functions), 1);
    }

    #[test]
    fn merges_function_tags_across_files() {
        let sources = vec![
            SourceFile {
                path: PathBuf::from("main.mcl"),
                text: "namespace demo; fn a() {} fn_tag t { value(a); }".to_owned(),
            },
            SourceFile {
                path: PathBuf::from("helper.mcl"),
                text: "namespace demo; fn main() { call #t(); }".to_owned(),
            },
        ];
        let program = frontend(&sources).unwrap();
        assert_eq!(program.function_tags.len(), 1);
        assert!(compile(&program, "test").is_ok());
    }
}
