mod analysis;
mod ast;
mod compiler;
mod diagnostic;
mod lexer;
mod lsp;
mod modules;
mod name_walk;
mod parser;
pub mod version;

use std::collections::{BTreeSet, HashMap, VecDeque};
use std::fs;
use std::path::{Component, Path, PathBuf};

use analysis::parse_all;
use compiler::{CompileOptions, CompiledPack, compile};
use diagnostic::Diagnostic;

pub use analysis::{
    FileDiagnostic, ProjectAnalysis, SourceFile, Span, Symbol, SymbolKind, analyze,
};
pub use compiler::DEFAULT_FUNCTION_PERMISSION_LEVEL;
pub use lsp::serve;

pub struct BuildOptions {
    pub description: String,
    pub deny_raw: bool,
    /// 数据包函数的最高权限等级（26.3 的 `function-permission-level`，默认 2）。
    pub function_permission_level: u8,
}

impl Default for BuildOptions {
    fn default() -> Self {
        Self {
            description: "Generated by mclang".into(),
            deny_raw: false,
            function_permission_level: DEFAULT_FUNCTION_PERMISSION_LEVEL,
        }
    }
}

/// `check` 的选项。
pub struct CheckOptions {
    pub function_permission_level: u8,
}

impl Default for CheckOptions {
    fn default() -> Self {
        Self {
            function_permission_level: DEFAULT_FUNCTION_PERMISSION_LEVEL,
        }
    }
}

#[derive(Debug)]
pub struct BuildResult {
    pub output: PathBuf,
    pub file_count: usize,
}

#[derive(Debug)]
pub struct CheckSummary {
    pub functions: usize,
    pub scores: usize,
    pub objectives: usize,
    pub queries: usize,
    pub item_stacks: usize,
    pub storages: usize,
    pub data_slots: usize,
    pub resources: usize,
    pub advancements: usize,
    pub function_tags: usize,
    pub raw_statements: usize,
}

pub fn check_file(source_path: &Path, options: &CheckOptions) -> Result<CheckSummary, String> {
    let loaded = read_project(source_path)?;
    let mut program = frontend(&loaded)?;
    compile(
        &mut program,
        &CompileOptions {
            description: "Generated by mclang".into(),
            function_permission_level: options.function_permission_level,
        },
    )
    .map_err(|diagnostics| render(&loaded.sources, diagnostics))?;
    Ok(CheckSummary {
        functions: program.functions.len(),
        scores: program.scores.len(),
        objectives: program.objectives.len(),
        queries: program.queries.len(),
        item_stacks: program.item_stacks.len(),
        storages: program.storages.len(),
        data_slots: program.data_slots.len(),
        resources: program.resources.len(),
        advancements: program.advancements.len(),
        function_tags: program.function_tags.len(),
        raw_statements: raw_statement_count(&program.functions),
    })
}

pub fn build_file(
    source_path: &Path,
    output: &Path,
    options: &BuildOptions,
) -> Result<BuildResult, String> {
    let loaded = read_project(source_path)?;
    let mut program = frontend(&loaded)?;
    let raw_statements = raw_statement_count(&program.functions);
    if options.deny_raw && raw_statements > 0 {
        return Err(format!(
            "严格模式拒绝构建：项目包含 {raw_statements} 条底层 run/execute 语句"
        ));
    }
    let pack = compile(
        &mut program,
        &CompileOptions {
            description: options.description.clone(),
            function_permission_level: options.function_permission_level,
        },
    )
    .map_err(|diagnostics| render(&loaded.sources, diagnostics))?;
    write_pack(output, &pack)?;
    Ok(BuildResult {
        output: output.to_path_buf(),
        file_count: pack.files.len(),
    })
}

fn raw_statement_count(functions: &[ast::Function]) -> usize {
    functions
        .iter()
        .map(|function| raw_count_in_block(&function.body))
        .sum()
}

fn raw_count_in_block(statements: &[ast::Statement]) -> usize {
    statements
        .iter()
        .map(|statement| match &statement.kind {
            ast::StatementKind::Run(_) => 1,
            ast::StatementKind::Return(ast::ReturnKind::Run(_)) => 1,
            ast::StatementKind::Execute {
                clauses: ast::ExecuteClauses::Raw(_),
                body,
            } => 1 + raw_count_in_block(body),
            ast::StatementKind::Execute {
                clauses: ast::ExecuteClauses::Structured(_),
                body,
            } => raw_count_in_block(body),
            ast::StatementKind::Each { body, .. }
            | ast::StatementKind::InDimension { body, .. }
            | ast::StatementKind::Spawn { body, .. }
            | ast::StatementKind::While { body, .. }
            | ast::StatementKind::For { body, .. } => raw_count_in_block(body),
            ast::StatementKind::Break | ast::StatementKind::Continue => 0,
            ast::StatementKind::If {
                then_body,
                else_body,
                ..
            } => raw_count_in_block(then_body) + raw_count_in_block(else_body),
            ast::StatementKind::Give { .. }
            | ast::StatementKind::EffectGive { .. }
            | ast::StatementKind::EffectClear { .. }
            | ast::StatementKind::XpChange { .. }
            | ast::StatementKind::StopwatchAction { .. }
            | ast::StatementKind::ClearInventory { .. }
            | ast::StatementKind::SetBlock { .. }
            | ast::StatementKind::Fill { .. }
            | ast::StatementKind::FillBiome { .. }
            | ast::StatementKind::Clone { .. }
            | ast::StatementKind::PlaceFeature { .. }
            | ast::StatementKind::PlaceJigsaw { .. }
            | ast::StatementKind::PlaceStructure { .. }
            | ast::StatementKind::PlaceTemplate { .. }
            | ast::StatementKind::ForceLoad(_)
            | ast::StatementKind::TimeAction { .. }
            | ast::StatementKind::Weather { .. }
            | ast::StatementKind::GameRuleSet { .. }
            | ast::StatementKind::WorldBorder(_)
            | ast::StatementKind::Locate { .. }
            | ast::StatementKind::SelfAction(_)
            | ast::StatementKind::Message { .. }
            | ast::StatementKind::PlaySound { .. }
            | ast::StatementKind::Call { .. }
            | ast::StatementKind::Let { .. }
            | ast::StatementKind::Schedule { .. }
            | ast::StatementKind::ScheduleClear { .. }
            | ast::StatementKind::Assign { .. }
            | ast::StatementKind::ScoreSet { .. }
            | ast::StatementKind::ScoreReset { .. }
            | ast::StatementKind::ScoreboardEnable { .. }
            | ast::StatementKind::ScoreboardOperation { .. }
            | ast::StatementKind::ScoreboardDisplay { .. }
            | ast::StatementKind::DataMerge { .. }
            | ast::StatementKind::DataRemove { .. }
            | ast::StatementKind::DataModify { .. }
            | ast::StatementKind::ItemAction { .. }
            | ast::StatementKind::Teleport { .. }
            | ast::StatementKind::NbtMerge { .. }
            | ast::StatementKind::AdvancementAction { .. }
            | ast::StatementKind::Return(_) => 0,
        })
        .sum()
}

/// 从磁盘加载的项目：可达模块的源文件与入口在其中的下标。
struct LoadedSources {
    sources: Vec<SourceFile>,
    root: usize,
}

/// 加载项目：入口是 `main.mcl`（目录输入）或给定文件（文件输入），
/// 其余模块沿 `import` 边按需读取；不可达的 `.mcl` 文件不参与编译。
fn read_project(path: &Path) -> Result<LoadedSources, String> {
    let metadata =
        fs::metadata(path).map_err(|error| format!("无法访问 {}：{error}", path.display()))?;
    let (entry, directory) = if metadata.is_file() {
        let directory = path
            .parent()
            .map_or_else(|| PathBuf::from("."), Path::to_path_buf);
        (path.to_path_buf(), directory)
    } else if metadata.is_dir() {
        let entry = path.join("main.mcl");
        if !entry.is_file() {
            return Err(format!(
                "目录 {} 缺少入口模块 main.mcl：项目根目录必须放入口模块，\
                 其余 .mcl 文件由入口用 `import 模块::路径;` 引入",
                path.display()
            ));
        }
        (entry, path.to_path_buf())
    } else {
        return Err(format!("输入 {} 不是普通文件或目录", path.display()));
    };

    let mut sources: Vec<SourceFile> = Vec::new();
    let mut indices: HashMap<PathBuf, usize> = HashMap::new();
    let mut queue: VecDeque<PathBuf> = VecDeque::new();
    let root = push_source(&mut sources, &mut indices, &entry)?;
    queue.push_back(entry);

    while let Some(file) = queue.pop_front() {
        let index = indices[&file];
        let text = &sources[index].text;
        // 语法错误会在统一的解析阶段报告；这里拿不到导入表就停止展开该分支。
        let imports = match lexer::lex(text, index) {
            Ok(tokens) => parser::parse(tokens).map(|program| program.imports).ok(),
            Err(_) => None,
        };
        let Some(imports) = imports else {
            continue;
        };
        for import in imports {
            let Some(target) = module_file(&directory, &import.path) else {
                continue;
            };
            if indices.contains_key(&target) {
                continue;
            }
            let target_index = push_source(&mut sources, &mut indices, &target)?;
            sources[target_index].path = target.clone();
            queue.push_back(target);
        }
    }

    Ok(LoadedSources { sources, root })
}

fn push_source(
    sources: &mut Vec<SourceFile>,
    indices: &mut HashMap<PathBuf, usize>,
    path: &Path,
) -> Result<usize, String> {
    let text = fs::read_to_string(path)
        .map_err(|error| format!("无法读取 {}：{error}", path.display()))?;
    let index = sources.len();
    indices.insert(path.to_path_buf(), index);
    sources.push(SourceFile {
        path: path.to_path_buf(),
        text,
    });
    Ok(index)
}

/// `import a::b;` 对应的文件：`<根目录>/a/b.mcl` 或 `<根目录>/a/b/mod.mcl`。
fn module_file(directory: &Path, segments: &[String]) -> Option<PathBuf> {
    let mut base = directory.to_path_buf();
    for segment in segments {
        base.push(segment);
    }
    let file = base.with_extension("mcl");
    if file.is_file() {
        return Some(file);
    }
    let directory_module = base.join("mod.mcl");
    directory_module.is_file().then_some(directory_module)
}

fn frontend(loaded: &LoadedSources) -> Result<ast::Program, String> {
    let (programs, diagnostics) = parse_all(&loaded.sources);
    if !diagnostics.is_empty() {
        return Err(render(&loaded.sources, diagnostics));
    }
    modules::resolve(programs, &loaded.sources, loaded.root)
        .map_err(|diagnostics| render(&loaded.sources, diagnostics))
}

/// 递归收集目录下的全部 `.mcl` 源文件（语言服务器用于发现工作区文件）。
pub(crate) fn discover_sources(directory: &Path, paths: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = fs::read_dir(directory)
        .map_err(|error| format!("无法读取目录 {}：{error}", directory.display()))?;
    for entry in entries {
        let entry = entry.map_err(|error| format!("无法读取目录项：{error}"))?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|error| format!("无法读取 {} 的类型：{error}", path.display()))?;
        if file_type.is_dir() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if !name.starts_with('.')
                && !matches!(name.as_ref(), "target" | "build" | "node_modules")
            {
                discover_sources(&path, paths)?;
            }
        } else if file_type.is_file()
            && path.extension().and_then(|extension| extension.to_str()) == Some("mcl")
        {
            paths.push(path);
        }
    }
    Ok(())
}

fn render(sources: &[SourceFile], diagnostics: Vec<Diagnostic>) -> String {
    diagnostics
        .into_iter()
        .map(|diagnostic| {
            let source = &sources[diagnostic.span.source];
            diagnostic.render(&source.path, &source.text)
        })
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn write_pack(output: &Path, pack: &CompiledPack) -> Result<(), String> {
    fs::create_dir_all(output)
        .map_err(|error| format!("无法创建输出目录 {}：{error}", output.display()))?;
    let manifest_path = output.join(".mclang-manifest");
    remove_old_outputs(output, &manifest_path)?;

    for (relative, contents) in &pack.files {
        let path = output.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("无法创建目录 {}：{error}", parent.display()))?;
        }
        fs::write(&path, contents)
            .map_err(|error| format!("无法写入 {}：{error}", path.display()))?;
    }

    let manifest = pack
        .files
        .keys()
        .map(|path| path.to_string_lossy().replace('\\', "/"))
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";
    fs::write(&manifest_path, manifest)
        .map_err(|error| format!("无法写入 {}：{error}", manifest_path.display()))
}

fn remove_old_outputs(output: &Path, manifest: &Path) -> Result<(), String> {
    let Ok(contents) = fs::read_to_string(manifest) else {
        return Ok(());
    };
    let mut paths = BTreeSet::new();
    for line in contents.lines() {
        let relative = Path::new(line);
        if line.is_empty()
            || relative.is_absolute()
            || relative
                .components()
                .any(|part| !matches!(part, Component::Normal(_)))
        {
            return Err(format!("拒绝使用损坏的构建清单 {}", manifest.display()));
        }
        paths.insert(relative.to_path_buf());
    }
    for relative in paths {
        let path = output.join(relative);
        match fs::remove_file(&path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(format!("无法清理旧输出 {}：{error}", path.display())),
        }
    }
    Ok(())
}
