use std::env;
use std::path::PathBuf;

use mclang::{BuildOptions, build_file, build_zip_file, check_file, serve};

fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let mut args = env::args().skip(1);
    let Some(command) = args.next() else {
        print_help();
        return Ok(());
    };

    match command.as_str() {
        "build" => {
            let source = args
                .next()
                .ok_or_else(|| "缺少源文件或项目目录\n\n运行 `mclang help` 查看用法".to_owned())?;
            let mut output = None;
            let mut description = "Generated by mclang".to_owned();
            let mut deny_raw = false;
            let mut zip = false;

            while let Some(arg) = args.next() {
                match arg.as_str() {
                    "-o" | "--output" => {
                        let value = args.next().ok_or_else(|| format!("{arg} 缺少目录参数"))?;
                        output = Some(PathBuf::from(value));
                    }
                    "--description" => {
                        description = args
                            .next()
                            .ok_or_else(|| "--description 缺少文本参数".to_owned())?;
                    }
                    "--deny-raw" => deny_raw = true,
                    "--zip" => zip = true,
                    _ => return Err(format!("未知参数 `{arg}`\n\n运行 `mclang help` 查看用法")),
                }
            }

            let source = PathBuf::from(source);
            let output = output.unwrap_or_else(|| {
                let name = if source.is_dir() {
                    source.file_name().and_then(|name| name.to_str())
                } else {
                    source.file_stem().and_then(|name| name.to_str())
                }
                .unwrap_or("datapack");
                let path = PathBuf::from("build").join(name);
                if zip {
                    path.with_extension("zip")
                } else {
                    path
                }
            });
            let options = BuildOptions {
                description,
                deny_raw,
            };
            let result = if zip {
                build_zip_file(&source, &output, &options)?
            } else {
                build_file(&source, &output, &options)?
            };
            println!(
                "已生成 {} 个文件：{}",
                result.file_count,
                result.output.display()
            );
            Ok(())
        }
        "check" => {
            let source = args
                .next()
                .ok_or_else(|| "缺少源文件或项目目录".to_owned())?;
            let mut deny_raw = false;
            for argument in args {
                match argument.as_str() {
                    "--deny-raw" => deny_raw = true,
                    _ => return Err(format!("未知参数 `{argument}`")),
                }
            }
            let summary = check_file(&PathBuf::from(source))?;
            if deny_raw && summary.raw_statements > 0 {
                return Err(format!(
                    "严格模式检查失败：项目包含 {} 条底层语句或不安全宏（run/execute/return run/运行期 with/nbt 宏片段）",
                    summary.raw_statements
                ));
            }
            println!(
                "检查通过：{} 个函数，{} 个计分变量，{} 个计分板目标，{} 个实体查询，{} 个物品定义，{} 个物品存储，{} 个数据槽，{} 个函数标签，{} 个 JSON 资源，{} 个进度，{} 条底层语句",
                summary.functions,
                summary.scores,
                summary.objectives,
                summary.queries,
                summary.item_stacks,
                summary.storages,
                summary.data_slots,
                summary.function_tags,
                summary.resources,
                summary.advancements,
                summary.raw_statements
            );
            Ok(())
        }
        "lsp" => {
            if args.next().is_some() {
                return Err("`mclang lsp` 不接受参数：它通过标准输入输出与编辑器通信".to_owned());
            }
            serve().map_err(|error| format!("语言服务器退出：{error}"))
        }
        "help" | "-h" | "--help" => {
            print_help();
            Ok(())
        }
        "version" | "-V" | "--version" => {
            println!("mclang {}", env!("CARGO_PKG_VERSION"));
            Ok(())
        }
        _ => Err(format!(
            "未知命令 `{command}`\n\n运行 `mclang help` 查看用法"
        )),
    }
}

fn print_help() {
    println!(
        "mclang — Minecraft 26.3 数据包编译器\n\n\
         用法:\n  \
            mclang build <源文件.mcl|项目目录> [-o <输出路径>] [--zip] [--description <文本>] [--deny-raw]\n  \
            mclang check <源文件.mcl|项目目录> [--deny-raw]\n  \
            mclang lsp\n  \
            mclang help\n\n\
         默认输出目录为 build/<源文件名>；--zip 改为 build/<源文件名>.zip。\n\
         项目可提供 assets/pack.png 与 assets/pack.mcmeta；后者可声明 formats、overlays、filter、features。\n\
         文件输入是单模块项目；目录输入以 <目录>/main.mcl 为入口模块，其他 .mcl 文件由 `import` 引入，\n\
         只有入口可达的模块会被编译。跨模块引用要求对方声明 `export`。\n\
         数据包函数固定按 GAMEMASTER 等级（2）校验，ADMIN/OWNER 命令不能用在 run 字符串中。\n\
         `mclang lsp` 是给编辑器用的语言服务器，不直接从终端运行。"
    );
}
